In [107]:
import numpy as np

In [108]:
X= np.array([[0,0,0],[0,1,1],[1,0,1],[1,1,0]])
Y = np.array([[0,0,0,1]]).T
X.shape, Y.shape

((4, 3), (4, 1))

In [109]:
def sig(z):
    return 1/(1+np.exp(-z))

In [110]:
weights = 2 *  np.random.random((3,1)) -1
#bias = 2 * np.random.random(1) -1
weights

array([[0.90783927],
       [0.6354484 ],
       [0.84842046]])

In [111]:
def derSig(z):
    return sig(z) * (1-sig(z))

In [112]:
def forward(x, weitghts):
    output0 = x
    input_o = np.dot(output0, weights)
    output1 = sig(input_o)
    return output1

In [113]:
forward(X,weights)

array([[0.5       ],
       [0.81515624],
       [0.8527406 ],
       [0.82394215]])

In [114]:
def train(x, y, weights , lr):
    for iter in range(10000):
        z = np.dot(x, weights)
        output1 = sig(z)
        
        first_term = output1 - y
        second_term = derSig(z)
        first_two_terms= first_term * second_term
        
        changes = np.array([[0.0],[0.0],[0.0]])
        
        for i in range(weights.shape[0]):
            for j in range(x.shape[0]):
                changes[i] += first_two_terms[j][0] * x[j][i]
        weights = weights - lr * changes
    return weights

In [116]:
final_weights = train(X,Y,weights,0.1)
final_weights , forward(X, final_weights)

(array([[ 1.80835834],
        [ 1.80376059],
        [-5.68429765]]), array([[0.5       ],
        [0.81515624],
        [0.8527406 ],
        [0.82394215]]))